BASE_URL = 'https://stellarburgers.nomoreparties.site'
CREATE_USER = f'{BASE_URL}/api/auth/register'
DELETE_USER = f'{BASE_URL}/api/auth/user'
LOGIN_USER = f'{BASE_URL}/api/auth/login'
CHANGE_USER_DATA = f'{BASE_URL}/api/auth/user'
CREATE_ORDER = f'{BASE_URL}/api/orders'
GET_USER_ORDER = f'{BASE_URL}/api/orders'